# Generated by Django 4.0.4 on 2022-05-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('1', '문의 등록'), ('2', '접수 완료'), ('3', '답변 완료')], default='', max_length=2, verbose_name='상태'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='message',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='문자메시지'),
        ),
    ]
